### ISSUE TITLE
Background colour lost when scrolling EPG display

### ISSUE THREAD

**Issue by dave-p** [PoulKalff/angularJS#5] opened 2020-09-07 08:32 UTC
![screenshot2](https://user-images.githubusercontent.com/3237636/92366037-886cc800-f0ec-11ea-8a07-448b6d5b6ef5.png)

The red background colour of the channel names is only shown on the initially visible page. If the page is scrolled the background for the later channel names is black.

Tested on Firefox and Chromium, both latest versions on Linux.

**Comment by PoulKalff** [comment] 2020-09-07 10:15
Yeah, I see...... I cannot reproduce it, though. I have only 8 channels, but if I stretch the browser over 2 screens, it shows the entire screen correctly, just with no channels after the 8th. The CSS is set to use the entire viewHeight:

#epg_channels {
    padding-left: 7px;
    padding-top: 3px;
    margin-top: 0px;
    **height: 100vh;**
    float: left;
    transition: .2s;
    background-color: maroon;
}

Could you investigate this for me further? If you INSPECT ELEMENT (in firefox) on the div, does it still show **height: 100vh;** ? If not, what then?

**Comment by dave-p** [comment] 2020-09-07 10:35
Setting height: auto on the 'body' style and on 'epg_channels' seems to do the trick. I suspect other styles with height:100% need changing too.
(edited to work round GitHub removing tagnames)

**Comment by PoulKalff** [comment] 2020-09-08 08:47
auto on the 'body' style only made it worse for me, but I think i have fixed it by setting 100vh on the body...... for some reason I can't figure out, the height of epg_channels was very, very erratic, but please see if it is not fixed by latest commit.

BTW: I notice you have no icons on channels, which I assume is because you have not added icons? I have, so I never thought about it..... but icons should obviously not be added if not present...

**Comment by dave-p** [comment] 2020-09-08 09:15
I still need to add height:auto to epg_channels.

Yes, dealing with all the different ways users have set up their TVHeadend is a real challenge...

Your index.html invokes a script "mtr-datepicker.min.js" which doesn't exist.

**Comment by PoulKalff** [comment] 2020-09-08 12:27
> I still need to add height:auto to epg_channels.
**Its already there, in the latest commit. I originally had 100vh, which probably should not used for child items, so it is change to 100% now, or rather, was in t he last commit**

> Yes, dealing with all the different ways users have set up their TVHeadend is a real challenge...
**Oh yes..... and it is impossible without feedback, so...**
 
> Your index.html invokes a script "mtr-datepicker.min.js" which doesn't exist.
**Yeah, there is a lot of cleanup left, especially in the css. I have left a lot of classes, because I might use them later. mtr-datepicker.min.js was an addon I experimented with previously, it is gone now.**

Are you satisfied with this ticket? If so, I'll close it. I'll work on the icons and the EPG-missing-line now, and make a new commit when it is done...... I have a job interview tomorrow, though, so it might not be done before tommorrow

**Comment by dave-p** [comment] 2020-09-08 12:42
epg_channels does need to be height:auto, not height:100%. See https://stackoverflow.com/questions/15943009/difference-between-css-height-100-vs-height-auto

Good luck for the interview!

**Comment by PoulKalff** [comment] 2020-09-08 12:52
Thanks.... yes, I know the difference, but It must to be 100% of the parent; if I set it to auto, it will only be the height of 8 channels (because "height: auto means the element height will depend upon the height of its children.") , and thus not fill out the screen. It works for you only because you have enough channels to fill up the screen.
Does 100% not work for you? ohh, yeah, because the channels that you have fill more than 100% of the screen...... so, all parents before must also be auto, in order to stretch the whole thing..... that's what you tried to explain before, right? ;-)

**Comment by PoulKalff** [comment] 2020-09-08 16:36
So, I have made a new commit with height: auto and min-height: 100%. Does that work for you?

**Comment by dave-p** [comment] 2020-09-08 16:54
YES! Well done!

**Comment by PoulKalff** [comment] 2020-09-08 17:02
Awesome, closing the ticket

**Closed as completed by PoulKalff** 2020-09-08 17:02 UTC
